name: Deploy

on:
  push:
    branches: [develop, main]

jobs:
  deploy:
    uses: twentythree-ch/github-workflows/.github/workflows/deploy-to-portainer.yml@main
    with:
      stack_name: ${{ github.event.repository.name }}  # Uses repo name as stack name
      portainer_url: "https://portainer.twentythree.ch"
      portainer_endpoint_id: "2"

    secrets:
      portainer_token: ${{ secrets.PORTAINER_TOKEN }}
      netbird_setup_key: ${{ secrets.NETBIRD_SETUP_KEY }}